### ISSUE TITLE
[BUG] No module named 'cornac.utils.fast_sparse_funcs'

### ISSUE THREAD

**Issue by thucnt** [PreferredAI/cornac#296]
### Description

cannot import cornac
### In which platform does it happen?

MacOSX

**Comment by saghiles** [comment]
Hi, can you please let us know how did you install Cornac.

**Comment by thucnt** [comment]
I used "conda install cornac -c conda-forge"

**Comment by saghiles** [comment]
I suspect this happens because the working directory is the Cornac folder. In this case, Python uses the source version of Cornac instead of the installed one. Hence, changing the working directory should fix the problem. If you wish to use the source version, you will need to build the Cornac Cython modules first.

**Comment by thucnt** [comment]
It's ok now. Thank you very much for your support.
