### ISSUE TITLE
[ASK] cornac on papers abstracts

### ISSUE THREAD

**Issue by x0rzkov** [PreferredAI/cornac#350]
Hi,

Hope you are all well !

I am looking for a recsys system and just wanted to ask you if your approach could apply to recommend arXiv papers.

More precisely, I have a dataset of 300k abstracts classified in tasks, subjects.
(available here https://paper2code.com/public/suggest_dump.txt.tar.gz)

How can I train a model based on this dataset ? Do you have a flask server for adding new entries and making queries ?

Ps. Also, do you have a dockerized version of cornac ?

Cheers,
X

**Comment by tqtg** [comment]
With your data containing item text, you might want to start with a few models tailored for such a scenario, e.g., `CTR`,  `CDL`, or `CVAE`.

Currently, we don't have a dockerized version of Cornac. However, a simple docker file with `python3` and `gfortran` should be enough for Cornac to operate.

**Comment by saghiles** [comment]
Hi @x0rzkov, 
I took a look at your data, and it seems like in addition to the article content (summary), you need to have preference information, in the form ``user_id, article_id, rating``, in order to consider the models suggested by @tqtg. See for instance [CiteUlike](https://cornac.readthedocs.io/en/latest/datasets.html#module-cornac.datasets.citeulike) dataset.

**Comment by x0rzkov** [comment]
Unfortunately, I do not have rating data, at least filled by user, for now. 

The only metric, for a sort of rating, that I have, is the average github stars for a paper as per the repository I match for each of them. 

And I have to confess that I am lost with all @tqtg acronyms. Can you explain them ?
For now, I am still in the cornac fog. 

Do you have any use case with a flask server api ? something that could apply to e-commerce or a blog
