### ISSUE TITLE
[ASK] How to interpret the rating in the UIR triplets

### ISSUE THREAD

**Issue by StijnVerdenius** [PreferredAI/cornac#394]
### Description

A fairly high-level question.

So, I have data of user-interactions with items. These are either click-tuples: `(user, item, has_clicked)` or sale-tuples `(user, item, has_bought)`. To combine these in the dataset, I want to use the "rating" in the cornac UIR triplet, but I am not sure how to interpret it and which values to choose. So here a couple of questions with regard to that:

- If I give a rating of `1` to clicks and a rating of `2` to sales, will this reach to goal of combining them both as positive ratings (but one stronger than the other), or will it see the clicks as negative (just like 1-5 stars in some of the sample datasets)? 
- Is it possible to give negative ratings, e.g. by rating `-1`, or does it still see that as a relative rating (less positive than e.g. `1`, but still positive nonetheless)?
- Could you give a high level guidance how to choose my rating values?

Currently mainly working with `BPR` and `VBPR` but probably going to try more models later

**Comment by tqtg** [comment]
Regarding your questions:

- If I give a rating of 1 to clicks and a rating of 2 to sales, will this reach to goal of combining them both as positive ratings (but one stronger than the other), or will it see the clicks as negative (just like 1-5 stars in some of the sample datasets)?
**Ans:** `this is implementation-dependent. For example, the current implementation of BPR treats ratings similarly, while VBPR takes into account the orders during training. We can't have an absolute answer to this because of different variants of implementation (even with other libraries). Please refer to the implementation of the models for more details.`

- Is it possible to give negative ratings, e.g. by rating -1, or does it still see that as a relative rating (less positive than e.g. 1, but still positive nonetheless)?
**Ans:** `again, this is implementation-dependent. BPR will just treat non-zero/observed ratings similarly as positive feedback, while VBPR will see -1 less positive than 1.`

Generally, most of the algorithms will treat observed ratings as positive, otherwise negative. If you consider some type of feedback as negative you can leave it out of your data.

Another thing you should care about is how the ratings will be used during the evaluation. This is controlled by `rating_threshold` argument of the [evaluation methods](https://cornac.readthedocs.io/en/latest/eval_methods.html).
