### ISSUE TITLE
[ASK] Image-based Dataset Interactions

### ISSUE THREAD

**Issue by RuihongQiu** [PreferredAI/cornac#400]
### Description

Hi,

Thank you for this great repo.

I have a few questions about the image-based dataset (Amazon Clothing and Tradesy) preprocessing.

(1) What's the chosen backbone to extract the image feature for these two datasets?

(2) Why are the numbers of users, items and interactions so small for Amazon Clothing (5,377 users | 3,393 items | 13,689 interactions), which has 278,677 ratings for the rich-features subset according to the [source website](http://jmcauley.ucsd.edu/data/amazon/)?

(3) How could I change the explicit feedback of Amazon Clothing to the implicit feedback?

Thank you in advance for your reply!

Best regards,

**Comment by tqtg** [comment]
(1) The features are original features provided [here](http://jmcauley.ucsd.edu/data/amazon)

(2) The Amazon Clothing dataset in Cornac is a subset of the original one. The size is smaller because items are filtered to make sure 3 types of modalities available (text, image, and graph). More details can be found [here](https://github.com/PreferredAI/cornac/blob/master/cornac/datasets/README.md#datasets)

(3) Not so clear about your question. Maybe you can define a threshold (rating > 4.0 as positive) and convert them into binary. Then you can consider them as implicit feedback. In addition, other types of feedback also available in the original dataset (views, clicks, purchases).

**Comment by RuihongQiu** [comment]
Thank you for your explanation.

So basically, if I want to only use the visual feature of Amazon Clothing, I can enlarge the dataset according to the original dataset since I only use the already extracted features from their original website.

But I can't download the visual feature from their 2014 version dataset, which always points to the 2019 version. And in the 2019 version, there is no pre-extracted visual features.

Could you suggest how to find it?

**Comment by tqtg** [comment]
I guess you can email the authors and ask for access to the data.

**Comment by RuihongQiu** [comment]
Thank you.

**Comment by RuihongQiu** [comment]
Actually, could you guys kindly provide the purely image-based Amazon Clothing dataset, since many recent papers use this dataset along with the Tradesy dataset. It would be much more convenient if we could have a similar dataset. :)

Thank you.

**Comment by tqtg** [comment]
Unfortunately, we don’t keep the original copy of the Amazon dataset.
