### ISSUE TITLE
how to prepare and add amazon datasets to cornac

### ISSUE THREAD

**Issue by poursistani** [PreferredAI/cornac#412]
### Description
hi
how can i add amazon boys and grirls clothing dataset to cornac

**Comment by tqtg** [comment]
@poursistani thanks for your interest in adding datasets into Cornac. 
First, you need to host the datasets somewhere so that they're available to access from the internet. Then, please take a look at our several [examples](https://github.com/PreferredAI/cornac/tree/master/cornac/datasets) and adapt for yours. Feel free to create a PR so that we can support.
