### ISSUE TITLE
BiVAECF imbalanced Itemclasses

### ISSUE THREAD

**Issue by Rico2000** [PreferredAI/cornac#431]
Hey,

I have a question regarding BiVAECF and the task of returning a ranking of products for users. My dataset is highly imbalanced and contains information about the interactions of about 3 million with 55 items. These interactions are iplicit feedback and thus only give information about positive interactions. 

Within the timeline I make a splid for testing the model. Thus, I echo more recent interactions for testing the model.

After training, I evaluate the model for raking metrics using the test dataset. Now the problem is that the model is not better than Most Popular. It has a similar to same ranking as MostPop, which is almost the same for every user. 
 
But within an item, it ranks positive interactionshigher than negative interactions. That means if I create a ROC for a product and the scores of the customers the result looks good. But not if I want to create a raking for items for the users.
Is there any way to fix or improve this problem?
Is there a possibility to set weights for each class or other techniques?

I hope my problem became more or less understandable.
Thanks for the help
Best regards
Rico

**Comment by saghiles** [comment]
Hi Rico, 

Given the very small number of items and the nature of the interactions (implicit), it's not surprising that the most popular approach does a good job. On average there is a high chance that a given user has interacted with most popular items, recommending the latter would therefore result in good performances.

Regarding user-sided and item-sided evaluations, the behavior you observe may also be explained by the size of the item set. If many users have mostly rated the same items (e.g., the popular ones) it's possible that the model fails to personalize user representations due to the user-encoder amortization. One quick way to check this hypothesis is to compare representations (\theta) across users.     

If the above hypothesis holds, I would recommend investigating the following two directions.
1. Collect more per-user data (basically increase the size of the item set). 
2. Drop the user-encoder so as to avoid amortizing inference on the user-side, which would correspond to a vanilla VAE applied on the item-side.

**Comment by Rico2000** [comment]
Hey,
thanks for your help. I will try your recommendations
