### ISSUE TITLE
[FEATURE] uid and iid maps serialized

### ISSUE THREAD

**Issue by deychak** [PreferredAI/cornac#460]
Hey Cornac team - is it possible to request a feature in the model saving routine that also stores the uid_map and iid_map maps on the object? The current implementation removes the train_set and val_set in the overriden __deepcopy__ method which is invoked in the saving routine. The issue is that if the model is saved to some remote location and loaded back in elsewhere, predictions can be made on a dataset specific index but we're not able to map back the original user/item IDs. In order to get around this, I've simply stored the train_set.uid_map and train_set.iid_map onto the model as an instance member before saving. Any thoughts on this?

**Comment by tqtg** [comment]
The reason we don't save train_set and val_set with the model is to reduce the model size, also to avoid duplicates when there are multiple models being experimented with. If you want to bring a model into production, serializing uid_map and iid_map into separate objects is a more reasonable approach because you need to implement serving API anyway.

**Comment by deychak** [comment]
Sure - that makes sense. In order to get around it for my use case, I did the following before saving.

```
model.uid_map = model.train_set.uid_map
```

**Comment by tqtg** [comment]
You can then serialize the train_set object separately and link with the model later on then. Current rank function uses train_set to check unknown users/items.

**Comment by deychak** [comment]
I found a way around this so I will close but it may be something to think about optionally adding onto the model's when saving.
