### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by ComeFromTheMars** [PreferredAI/cornac#603]
### Other Comments
Hello, I am a novice programmer and I have encountered some difficulties while training recommendation models using your code. The number of users I set, the data of the project, and the number of interactions between them are all different. During training, the following error always occurs: "Value Error: row, column, and data array must all be the same length." If this is the case, modifying the code there can solve the problem. Thank you

**Comment by darrylong** [comment]
Hi there,

Thanks for sharing. Would like to know how's your data like and what you're trying to achieve.

Here are some quick documentations that may help you:

**How to use your own data**
https://cornac.readthedocs.io/en/stable/user/owndata.html

**Training/Recommending/Deploying a service**
https://cornac.readthedocs.io/en/stable/user/iamadeveloper.html

Please feel free to let us know on the issues you face, so that we can improve these documentations as well.

Thanks!

**Comment by ComeFromTheMars** [comment]
Thank you very much for your letter. As a new programmer, I didn't expect to receive a response to any questions I asked. Based on your technical documentation, I have already solved my problem. Thank you for your help



At 2024-03-19 11:45:25, "darrylong" ***@***.***> wrote:

Hi there,

Thanks for sharing. Would like to know how's your data like and what you're trying to achieve.

Here are some quick documentations that may help you:

How to use your own data
https://cornac.readthedocs.io/en/stable/user/owndata.html

Training/Recommending/Deploying a service
https://cornac.readthedocs.io/en/stable/user/iamadeveloper.html

Please feel free to let us know on the issues you face, so that we can improve these documentations as well.

Thanks!

**Comment by darrylong** [comment]
Our pleasure! Feel free to reach out to us if you need more help!
