### ISSUE TITLE
[FEATURE] Categorizing models by supported modalities

### ISSUE THREAD

**Issue by lthoang** [PreferredAI/cornac#634]
### Description

We need a document for models' supported modalities for ease of model selection.

**Comment by darrylong** [comment]
I suggest that we could have another table, similar to in PR #624 and #632 that will be on readthedocs as well (below the original table). 

This table could show models with different modalities supported (similar to the PyTorch/TensorFlow columns). 

In order to obtain the modalities supported, we could run a script to go through the model files to look for the following keywords (e.g. 'sentiment', 'user_image'), as detailed in the BaseMethod file below.

https://github.com/PreferredAI/cornac/blob/ef9956e6a4549953820baa15275066ca405a0204/cornac/eval_methods/base_method.py#L281-L290
